#' @importFrom assertthat assert_that
#' @export
rtypeform_set_scope = function(scopes = NULL){
  if(!is.null(scopes)){
    assert_that(is.character(scopes))
    options("rtypeform.scopes_selected" = scopes)
  }
}

#' @importFrom assertthat assert_that
#' @export
rtypeform_set_client_id = function(id = NULL){
  if(!is.null(id)){
    assert_that(is.character(id))
    options("rtypeform.client_id" = id)
  }
}

#' @importFrom assertthat assert_that
#' @export
rtypeform_set_client_secret = function(secret = NULL){
  if(!is.null(secret)){
    assert_that(is.character(secret))
    options("rtypeform.client_secret" = secret)
  }
}

#' @importFrom assertthat assert_that
#' @export
rtypeform_set_webapp_client_id = function(id = NULL){
  if(!is.null(id)){
    assert_that(is.character(id))
    options("rtypeform.webapp.client_id" = id)
  }
}

#' @importFrom assertthat assert_that
#' @export
rtypeform_set_webapp_client_secret = function(secret = NULL){
  if(!is.null(secret)){
    assert_that(is.character(secret))
    options("rtypeform.webapp.client_secret" = secret)
  }
}

#' @export
rtypeform_set_token = function(token){
  # if the token is an ouath token generated by make_new_token
  if(inherits(token,"Token2.0")){
    Sys.setenv("typeform_api2" = token$credentials$access_token)
  }else if(is.character(token)){
    # if it's a personal token
    Sys.setenv("typeform_api2" = token)
  }else{
    stop("Token is neither an Oauth Token2.0 as created using make_new_token, nor a string for a personal access token")
  }

}
